package esprit.petrofactory.interfaces;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

public class FXManagmentController {
	@FXML
	private Button bnt1;
	@FXML
	private Button btn2;
	@FXML
	private Button btn3;
	@FXML
	private Button btn4;

	// Event Listener on Button[#bnt1].onMouseClicked
	@FXML
	public void Gaspump(MouseEvent event) {
		 FXMLLoader loader = new FXMLLoader(getClass().getResource("./FXGasPump.fxml"));
         Parent root;
         try {
             root = loader.load();
             
             bnt1.getScene().setRoot(root);
             
         } catch (IOException ex) {
             //Logger.getLogger(AjoutDiscussionFXMLController.class.getName()).log(Level.SEVERE, null, ex);
         System.out.println("error");
         }	}
	// Event Listener on Button[#btn2].onMouseClicked
	@FXML
	public void Pumpmeter(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn3].onMouseClicked
	@FXML
	public void Fuelorder(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn4].onMouseClicked
	@FXML
	public void report(MouseEvent event) {
		// TODO Autogenerated
	}
}
